### ISSUE TITLE
need help runing this project

### ISSUE THREAD

**Issue by abdulashfaq** [nhd36/OCR_Management#2]
hello sir/,madam,

i need help run this project and i also acquired the google cloud api key  but don't know how to link so please can you help

you can contact me 
on my mail id : abdulashfaq.info@gmail.com
or my mobile number of India  : 9701042412

expecting a  quick reply sir/madam
thank you

**Comment by nhd36** [comment]
Hello there,

I was using an external API to do the OCR job. Unfortunately, I cannot share the credentials of the API with you. In that case, did you follow the instruction on the README.md file?

**Comment by abdulashfaq** [comment]
Yeah i followed the readme.md file and i cannot run the project

If you can say which api you used i will create an in that api providing company

And actually if you can connect me through teamviewer it will very helpful for me

**Comment by nhd36** [comment]
When do you need to get it run? At the moment, I am a bit busy so I won't be able to help in-depth. Are you familiar with Docker? If yes, I will try to build a docker file and docker-compose for you.

**Comment by abdulashfaq** [comment]
I am free this whole month and i don't know
how to use docker

And i require your help in running this project
So if you can contact or explain it to me thorough TeamViewer it would be
great help for me .

When your free please do contact our reply through email

Thank you

**Comment by nhd36** [comment]
Alright, I will get back to you when I'm free. Then I will let you know when we can do the TeamViewer

**Comment by nhd36** [comment]
Probably needs to fix some code in order for it to run too :D

**Comment by abdulashfaq** [comment]
Dear sir,

 

If u can contact me within this week it will a great help for me

 

Thank you

 

Regards

Md Abdul Ashfaq Khan

**Comment by abdulashfaq** [comment]
hello sir,

I am waiting for your reply sir and can you please contact me within this
week of 07/06/2021 to 13/06/2021
i kind need to finish this project and need to submit it in my college as a
major project
so please understand sir i need to complete the project within this month

so please can you contact me within this week

Thank You

Regards
MD ABDUL ASHFAQ KHAN

**Comment by nhd36** [comment]
I will be finishing with my finals this weekend. I am not sure if I want to do Team Viewer since I don't usually do Team Viewer with strangers and have no experience using Team Viewer. But I will write details what you need to do and have a chat about how the project run. I was able to set it up on my cloud server last week.  I will contact you during the weekend.

**Comment by abdulashfaq** [comment]
Ok thank you sir

**Comment by abdulashfaq** [comment]
Hello  sir,

When will you be available, For explaining the execution project today or
tomorrow, If tomorrow can you specify at what time will you be available.

Waiting for your reply
Thank you

Regards
Ashfaq Khan

**Comment by nhd36** [comment]
I'm gonna post everything on README.

**Comment by abdulashfaq** [comment]
ok thank you sir i will be waiting for the update

**Comment by nhd36** [comment]
I finished updating the README. Let me know if there is any problem. Post the error in the comment section so I can see it.

**Comment by abdulashfaq** [comment]
sir can this able to run on a windows machine

**Comment by nhd36** [comment]
Yes, as long as you have Python3 on your machine. Screenshot your error and put them in the codeblock for me please

**Comment by abdulashfaq** [comment]
sir which api's you used for cloud and ocr as api key and what is the JWT_SECRET KEY from where can i get those key's please help me

and i dual booted my laptop today and installed ubuntu 20.0.4 LTS 
and if you which company is providing those  api key's then it will be helpful for me
Thank You

**Comment by nhd36** [comment]
I was using the API from my ex-company (ComputerVisionVietnam). It was internal usage, so if you want to use it, I bet you gonna have to pay for the APIs. JWT_SECRET_KEY is the key you can generate randomly to secure your JsonWeb Token

**Comment by abdulashfaq** [comment]
hello sir everything working fine except the read image page
after uploading the image it's showing unable to scan the image error 
so can u please send me the js file fo retrieving information from the image and iam using google cloud stroage and google cloud vision api's for this project 

so please help me solve this error 

thank you
![Screenshot from 2021-06-15 23-48-06](https://user-images.githubusercontent.com/63793027/122103464-44091800-ce34-11eb-956b-a3139aeb2906.png)

**Comment by nhd36** [comment]
Can you send me the response of your Google Cloud API?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by abdulashfaq** [comment]
means the document upload right 
it's working fine i am running my windows machine after i boot to the ubuntu machine i will  be sending it soon 
i am actually documenting my peoject windows so after i finsih it will send the GOOGLE  CLOUD API response

Thank You

**Comment by abdulashfaq** [comment]
hello sir can u record the procedure using google cloud i cant seem to upload the project to the gcloud and run it through google cloud

**Comment by nhd36** [comment]
what do you mean by run it Google Cloud? You mean deployment?

**Comment by abdulashfaq** [comment]
Yes

**Comment by nhd36** [comment]
Man, I can't help you with all the problems you have. You gotta figure it by yourself. https://cloud.google.com/appengine/docs/standard/python/getting-started/deploying-the-application Here is the source you can use for reference

**Comment by abdulashfaq** [comment]
Hello bro can you please contact me

**Comment by abdulashfaq** [comment]
it's very urgent please please please
contact no: +91 9701042412
Email ID: abdulashfaq.info@gmail.com

**Comment by abdulashfaq** [comment]
can u please contact me personally not through github page
i need to contact you please very urgent
please BRO need help

**Comment by abdulashfaq** [comment]
Bro can u please share the API of your's mine are not working for this project i even contacted the company of ComputerVisionVietnam but they said they wont support other than vietnam country so i need the API of this project  i can't use the GOOGLE API's on this project it's giving me error or the image is unable to load so can u please share the .env files for both front end and back end just for tommorow  it will help me

**Comment by abdulashfaq** [comment]
Tommorow is my major project submission please bro help me out
or if you can help me through google meet or zoom i will be helpful

**Comment by abdulashfaq** [comment]
I am willing t pay for the services that you provide for just tommrow so please help me out

**Comment by nhd36** [comment]
As I said, let me see your Google API. I am not very comfortable contacting strangers. I already made the document as easy as possible for you to be able to run the project. I don't need the money. This is how far I can help you. Plus if it is a major project, shouldn't you just do it your own instead of cloning a public project and asking for help from a stranger?

**Comment by abdulashfaq** [comment]
Sorry and thank you for your project i successfully used the Google api and
running it that you for your project

**Comment by abdulashfaq** [comment]
Thank you for your support and your help
